// Code generated by golex. DO NOT EDIT.

// Copyright 2017 The Prometheus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package textparse

import (
	"fmt"
)

const (
	sInit = iota
	sComment
	sMeta1
	sMeta2
	sLabels
	sLValue
	sValue
	sTimestamp
)

// Lex is called by the parser generated by "go tool yacc" to obtain each
// token. The method is opened before the matching rules block and closed at
// the end of the file.
func (l *lexer) Lex() token {
	if l.i >= len(l.b) {
		return tEOF
	}
	c := l.b[l.i]
	l.start = l.i

yystate0:

	switch yyt := l.state; yyt {
	default:
		panic(fmt.Errorf(`invalid start condition %d`, yyt))
	case 0: // start condition: INITIAL
		goto yystart1
	case 1: // start condition: sComment
		goto yystart25
	case 2: // start condition: sMeta1
		goto yystart28
	case 3: // start condition: sMeta2
		goto yystart30
	case 4: // start condition: sLabels
		goto yystart33
	case 5: // start condition: sLValue
		goto yystart38
	case 6: // start condition: sValue
		goto yystart42
	case 7: // start condition: sTimestamp
		goto yystart45
	}

	goto yystate0 // silence unused label error
	goto yystate1 // silence unused label error
yystate1:
	c = l.next()
yystart1:
	switch {
	default:
		goto yyabort
	case c == '#':
		goto yystate6
	case c == ':' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate24
	case c == '\n':
		goto yystate4
	case c == '\r':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate3
	case c == '\x00':
		goto yystate2
	}

yystate2:
	c = l.next()
	goto yyrule1

yystate3:
	c = l.next()
	switch {
	default:
		goto yyrule3
	case c == '\t' || c == ' ':
		goto yystate3
	}

yystate4:
	c = l.next()
	goto yyrule2

yystate5:
	c = l.next()
	switch {
	default:
		goto yyabort
	case c == '\n':
		goto yystate4
	}

yystate6:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c == ' ':
		goto yystate13
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= '\x1f' || c >= '!' && c <= 'ÿ':
		goto yystate7
	}

yystate7:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate8
	}

yystate8:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate9
	}

yystate9:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate10
	}

yystate10:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate11
	}

yystate11:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate12
	}

yystate12:
	c = l.next()
	goto yyrule6

yystate13:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c == 'H':
		goto yystate14
	case c == 'T':
		goto yystate19
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'G' || c >= 'I' && c <= 'S' || c >= 'U' && c <= 'ÿ':
		goto yystate8
	}

yystate14:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c == 'E':
		goto yystate15
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'D' || c >= 'F' && c <= 'ÿ':
		goto yystate9
	}

yystate15:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c == 'L':
		goto yystate16
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'K' || c >= 'M' && c <= 'ÿ':
		goto yystate10
	}

yystate16:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c == 'P':
		goto yystate17
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'O' || c >= 'Q' && c <= 'ÿ':
		goto yystate11
	}

yystate17:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c == ' ':
		goto yystate18
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= '\x1f' || c >= '!' && c <= 'ÿ':
		goto yystate12
	}

yystate18:
	c = l.next()
	goto yyrule4

yystate19:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c == 'Y':
		goto yystate20
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'X' || c >= 'Z' && c <= 'ÿ':
		goto yystate9
	}

yystate20:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c == 'P':
		goto yystate21
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'O' || c >= 'Q' && c <= 'ÿ':
		goto yystate10
	}

yystate21:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c == 'E':
		goto yystate22
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'D' || c >= 'F' && c <= 'ÿ':
		goto yystate11
	}

yystate22:
	c = l.next()
	switch {
	default:
		goto yyrule6
	case c == ' ':
		goto yystate23
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= '\x1f' || c >= '!' && c <= 'ÿ':
		goto yystate12
	}

yystate23:
	c = l.next()
	goto yyrule5

yystate24:
	c = l.next()
	switch {
	default:
		goto yyrule10
	case c >= '0' && c <= ':' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate24
	}

	goto yystate25 // silence unused label error
yystate25:
	c = l.next()
yystart25:
	switch {
	default:
		goto yyrule7
	case c == '\t' || c == ' ':
		goto yystate27
	case c >= '\x01' && c <= '\b' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '\x1f' || c >= '!' && c <= 'ÿ':
		goto yystate26
	}

yystate26:
	c = l.next()
	switch {
	default:
		goto yyrule7
	case c >= '\x01' && c <= '\t' || c == '\v' || c == '\f' || c >= '\x0e' && c <= 'ÿ':
		goto yystate26
	}

yystate27:
	c = l.next()
	switch {
	default:
		goto yyrule3
	case c == '\t' || c == ' ':
		goto yystate27
	case c >= '\x01' && c <= '\b' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '\x1f' || c >= '!' && c <= 'ÿ':
		goto yystate26
	}

	goto yystate28 // silence unused label error
yystate28:
	c = l.next()
yystart28:
	switch {
	default:
		goto yyabort
	case c == ':' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate29
	case c == '\t' || c == ' ':
		goto yystate3
	}

yystate29:
	c = l.next()
	switch {
	default:
		goto yyrule8
	case c >= '0' && c <= ':' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate29
	}

	goto yystate30 // silence unused label error
yystate30:
	c = l.next()
yystart30:
	switch {
	default:
		goto yyabort
	case c == '\t' || c == ' ':
		goto yystate32
	case c >= '\x01' && c <= '\b' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '\x1f' || c >= '!' && c <= 'ÿ':
		goto yystate31
	}

yystate31:
	c = l.next()
	switch {
	default:
		goto yyrule9
	case c >= '\x01' && c <= '\t' || c == '\v' || c == '\f' || c >= '\x0e' && c <= 'ÿ':
		goto yystate31
	}

yystate32:
	c = l.next()
	switch {
	default:
		goto yyrule3
	case c == '\t' || c == ' ':
		goto yystate32
	case c >= '\x01' && c <= '\b' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '\x1f' || c >= '!' && c <= 'ÿ':
		goto yystate31
	}

	goto yystate33 // silence unused label error
yystate33:
	c = l.next()
yystart33:
	switch {
	default:
		goto yyabort
	case c == ',':
		goto yystate34
	case c == '=':
		goto yystate35
	case c == '\t' || c == ' ':
		goto yystate3
	case c == '}':
		goto yystate37
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate36
	}

yystate34:
	c = l.next()
	goto yyrule15

yystate35:
	c = l.next()
	goto yyrule14

yystate36:
	c = l.next()
	switch {
	default:
		goto yyrule12
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate36
	}

yystate37:
	c = l.next()
	goto yyrule13

	goto yystate38 // silence unused label error
yystate38:
	c = l.next()
yystart38:
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate39
	case c == '\t' || c == ' ':
		goto yystate3
	}

yystate39:
	c = l.next()
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate40
	case c == '\\':
		goto yystate41
	case c >= '\x01' && c <= '!' || c >= '#' && c <= '[' || c >= ']' && c <= 'ÿ':
		goto yystate39
	}

yystate40:
	c = l.next()
	goto yyrule16

yystate41:
	c = l.next()
	switch {
	default:
		goto yyabort
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate39
	}

	goto yystate42 // silence unused label error
yystate42:
	c = l.next()
yystart42:
	switch {
	default:
		goto yyabort
	case c == '\t' || c == ' ':
		goto yystate3
	case c == '{':
		goto yystate44
	case c >= '\x01' && c <= '\b' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '\x1f' || c >= '!' && c <= 'z' || c >= '|' && c <= 'ÿ':
		goto yystate43
	}

yystate43:
	c = l.next()
	switch {
	default:
		goto yyrule17
	case c >= '\x01' && c <= '\b' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '\x1f' || c >= '!' && c <= 'z' || c >= '|' && c <= 'ÿ':
		goto yystate43
	}

yystate44:
	c = l.next()
	goto yyrule11

	goto yystate45 // silence unused label error
yystate45:
	c = l.next()
yystart45:
	switch {
	default:
		goto yyabort
	case c == '\n':
		goto yystate46
	case c == '\r':
		goto yystate47
	case c == '\t' || c == ' ':
		goto yystate3
	case c >= '0' && c <= '9':
		goto yystate48
	}

yystate46:
	c = l.next()
	goto yyrule19

yystate47:
	c = l.next()
	switch {
	default:
		goto yyabort
	case c == '\n':
		goto yystate46
	}

yystate48:
	c = l.next()
	switch {
	default:
		goto yyrule18
	case c >= '0' && c <= '9':
		goto yystate48
	}

yyrule1: // \0
	{
		return tEOF
	}
yyrule2: // \r?\n
	{
		l.state = sInit
		return tLinebreak
		goto yystate0
	}
yyrule3: // [ \t]+
	{
		return tWhitespace
	}
yyrule4: // #\ HELP\
	{
		l.state = sMeta1
		return tHelp
		goto yystate0
	}
yyrule5: // #\ TYPE\
	{
		l.state = sMeta1
		return tType
		goto yystate0
	}
yyrule6: // #.?.?.?.?.?.?
	{
		// Hack to make comments work that start with a prefix
		// of the above two rules. The generator does not
		// seem to do the right thing here.
		l.state = sComment
		goto yystate0
	}
yyrule7: // [^\r\n]*
	{
		l.state = sInit
		return tComment
		goto yystate0
	}
yyrule8: // {M}({M}|{D})*
	{
		l.state = sMeta2
		return tMName
		goto yystate0
	}
yyrule9: // [^\n\r]+
	{
		l.state = sInit
		return tText
		goto yystate0
	}
yyrule10: // {M}({M}|{D})*
	{
		l.state = sValue
		return tMName
		goto yystate0
	}
yyrule11: // \{
	{
		l.state = sLabels
		return tBraceOpen
		goto yystate0
	}
yyrule12: // {L}({L}|{D})*
	{
		return tLName
	}
yyrule13: // \}
	{
		l.state = sValue
		return tBraceClose
		goto yystate0
	}
yyrule14: // =
	{
		l.state = sLValue
		return tEqual
		goto yystate0
	}
yyrule15: // ,
	{
		return tComma
	}
yyrule16: // \"(\\.|[^\\"])*\"
	{
		l.state = sLabels
		return tLValue
		goto yystate0
	}
yyrule17: // [^{ \t\n\r]+
	{
		l.state = sTimestamp
		return tValue
		goto yystate0
	}
yyrule18: // {D}+
	{
		return tTimestamp
	}
yyrule19: // \r?\n
	{
		l.state = sInit
		return tLinebreak
		goto yystate0
	}
	panic("unreachable")

	goto yyabort // silence unused label error

yyabort: // no lexem recognized
	return tInvalid
}
